### ISSUE TITLE
Problems compiling listener_c and talker_c for BOARD=samr21-xpro

### ISSUE THREAD

**Issue by jlamperez** [astralien3000/riot-ros2#1]
Hi @astralien3000,

First of all, great job porting ros2 on microcontrollers with RIOT.

Yesterday when I was trying to compile _listener_c_ and _talker_c_ for smar21-xpro I was experimenting the next error

```
/home/jlamperez/Workspace/riot-ros2/src/rmw/error_handling.c:27:38: error: __emutls_t.__rmw_error_state causes a section type conflict with __rmw_error_state
 RMW_THREAD_LOCAL rmw_error_state_t * __rmw_error_state = NULL;
                                      ^
/home/jlamperez/Workspace/riot-ros2/src/rmw/error_handling.c:27:38: note: '__rmw_error_state' was declared here
/home/jlamperez/Workspace/riot-ros2/RIOT/Makefile.base:81: recipe for target '/home/jlamperez/Workspace/riot-ros2/examples/talker_c/bin/samr21-xpro/rmw/error_handling.o' failed
make[3]: *** [/home/jlamperez/Workspace/riot-ros2/examples/talker_c/bin/samr21-xpro/rmw/error_handling.o] Error 1
make[3]: Leaving directory '/home/jlamperez/Workspace/riot-ros2/src/rmw'
/home/jlamperez/Workspace/riot-ros2/RIOT/Makefile.base:20: recipe for target 'ALL--/home/jlamperez/Workspace/riot-ros2/src/rmw' failed
make[2]: *** [ALL--/home/jlamperez/Workspace/riot-ros2/src/rmw] Error 2
make[2]: Leaving directory '/home/jlamperez/Workspace/riot-ros2'
/home/jlamperez/Workspace/riot-ros2/RIOT/Makefile.base:20: recipe for target 'ALL--/home/jlamperez/Workspace/riot-ros2' failed
make[1]: *** [ALL--/home/jlamperez/Workspace/riot-ros2] Error 2
make[1]: Leaving directory '/home/jlamperez/Workspace/riot-ros2/examples/talker_c'
/home/jlamperez/Workspace/riot-ros2/examples/talker_c/../../RIOT/Makefile.include:297: recipe for target 'all' failed
make: *** [all] Error 2

``` 

The command I used inside _riot-ros2/examples/talker_c_ was 

```
make RMW=rmw_mqtt BOARD=samr21-xpro
```

Do you know how to solve it to allow me to flash the board?

Thank you for your time.

Jorge

**Comment by astralien3000** [comment]
Hi @jlamperez,

Thank you for your feedback !

I'm sorry, currently the rmw_mqtt version is not very stable. Which version are you using ? mqtt is not likely to work on the master branch. You can use the branches v0.0 or v0.1 for it.

If you were already on these versions, I will try to investigate. What is your OS ?

**Comment by jlamperez** [comment]
Hi @astralien3000,

Thank you for answer to me, right now I am using the master branch of your repository and same happens to me when I try ndn. 

I will try with the branches you say me.

My OS is Ubuntu 16.04.

**Comment by astralien3000** [comment]
I don't have Ubuntu to test right now, only Fedora. I can't get the same error on Fedora. I will try to get an Ubuntu.
Just to know, what is your version of `arm-none-eabi-gcc` ?

Also, it seems like the rmw_mqtt version was already broken in v0.1 ^^", only v0.0 can currently compile with mqtt.

**Comment by jlamperez** [comment]
> Just to know, what is your version of `arm-none-eabi-gcc` ?

I am using arm-none-eabi-gcc (15:4.9.3+svn231177-1) 4.9.3 20150529 (prerelease)

**Comment by astralien3000** [comment]
Ok, this version is supposed to be ok for RIOT, but maybe too old for some ROS2 code.
First, you could try to remove the `bin` directory in the example, to ensure there is no error from previous compilation, and retry `make BOARD=samr21-xpro`.

If it fails again, you can try to [update the arm-none-eabi toolchain](https://github.com/RIOT-OS/RIOT/wiki/Family%3A-ARM).

**Comment by astralien3000** [comment]
Well, the previous link is not so clear.
I could make it work on ubuntu 16.04 : 
```bash
# Remove old toolchain
sudo apt remove gcc-arm-none-eabi
sudo apt autoremove

# Install new toolchain
sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa
sudo apt-get update
sudo apt install gcc-arm-embedded
```
Does it help ?

**Comment by jlamperez** [comment]
Hi @astralien3000 

I updated the arm-none-eabi toolchain to version 6.3 and it worked.

Thanks!

**Comment by astralien3000** [comment]
You're welcome !
